
abstract class FFAppConstants {
  static const List<String> statusList = [
    'ACCEPTED AUTOMATICALLY, FINALIZED',
    'NOT SYNCHRONIZED, CLIENT-SIDE PROBLEM',
    'NOT SYNCHRONIZED, INTEGRATION PROBLEM',
    'CANCELLED',
    'REJECTED BY MODERATOR',
    'REJECTED AUTOMATICALLY DEFINITELY',
    'NOT ACCEPTED OR AWAITING',
    'ACCEPTED AUTOMATICALLY, NOT FINALIZED',
    'ACCEPTED BY MODERATOR',
    'ACCEPTED BY USER, NOT FINALIZED'
  ];
  static const List<String> rejectionReasonList = [
    'DUPLICATE',
    'INCOMPLETE_PHOTO',
    'UNREADABLE',
    'NO_RECEIPT',
    'WRONG_DATE',
    'WRONG_SHOP',
    'NO_PROM_PRODUCT',
    'RULES_NOT_MET',
    'MANUAL_INGERENTION'
  ];
}
